# Generated by Django 3.0.5 on 2020-05-11 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_order_billing_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='image_name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
