# Generated by Django 3.0.5 on 2020-05-11 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_item_image_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='availability',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('S', 'Shirt'), ('SW', 'Sport Wear'), ('OW', 'Out wear'), ('G', 'Gases'), ('C', 'Chemicals')], max_length=2),
        ),
    ]
